name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image to Registry
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USER }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          echo $HARBOR_PASSWORD | docker login $REGISTRY -u $HARBOR_USER --password-stdin
          docker push $IMAGE_NAME:${{ github.sha }}
