name: Security Scan

on: [push]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: github/dependency-review-action@v2

      - name: Set up Snyk
        uses: snyk/actions/setup@v1
        with:
          version: 'latest'

      - name: Run Snyk Security Scan
        uses: snyk/actions/snyk@v1
        with:
          continue-on-error: true
